# Generated by Django 5.2.8 on 2025-12-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
                ('comercio', models.CharField(max_length=255)),
                ('contacto', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('compra_cjs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compra_pzs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('venta_cjs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('venta_pzs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
